# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImpactRasterCreator
                                 A QGIS plugin
 This plugin generates flood impact maps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-07-11
        copyright            : (C) 2019 by Anthony Cooper
        email                : anthony.cooper@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ImpactRasterCreator class from file ImpactRasterCreator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .impact_raster_creator import ImpactRasterCreator
    return ImpactRasterCreator(iface)
